### ISSUE TITLE
Extra function

### ISSUE THREAD

**Issue by carsonliu1** [animalStyleFries/FrontEndCapstone-EcommercePage#31]
https://github.com/animalStyleFries/FrontEndCapstone-EcommercePage/blob/8881c4df4a3869bb0ac8480981a161b83ab773f9/client/src/Main/WidgetRandy/Components/ImageGallery.jsx#L23-L25

Since this function is being used at the same file as its state, theres no need to create a function to invoke the state funciton.

**Comment by RandyIp** [comment]
Removed extra function.
