### ISSUE TITLE
If statements

### ISSUE THREAD

**Issue by carsonliu1** [animalStyleFries/FrontEndCapstone-EcommercePage#32]
https://github.com/animalStyleFries/FrontEndCapstone-EcommercePage/blob/2077ba5877110ff56934a42a90464e70d097e7e7/client/src/Main/WidgetRandy/Components/ProductInformation.jsx#L23-L27

Instead of having all of these if statements to round to nearest 25, you can use math to do it. Math.round(number * 4) / 4).toFixed(2)

**Comment by RandyIp** [comment]
Sick

Added
