### ISSUE TITLE
Unused imports should be removed

### ISSUE THREAD

**Issue by carsonliu1** [animalStyleFries/FrontEndCapstone-EcommercePage#34]
https://github.com/animalStyleFries/FrontEndCapstone-EcommercePage/blob/2077ba5877110ff56934a42a90464e70d097e7e7/client/src/Main/WidgetMonica/components/BottomSide/MoreAnsweredQuestions.jsx#L1

**Comment by MonicaLiu828** [comment]
Ok, thx for the suggestion, accept and modified~
