### ISSUE TITLE
Remove unused code and console logs

### ISSUE THREAD

**Issue by carsonliu1** [animalStyleFries/FrontEndCapstone-EcommercePage#35]
https://github.com/animalStyleFries/FrontEndCapstone-EcommercePage/blob/2077ba5877110ff56934a42a90464e70d097e7e7/client/src/Main/WidgetMonica/components/MiddleSide/IndividualQuestion.jsx#L9-L11

**Comment by RandyIp** [comment]
Removed console.logs, thanks Carson!
