### ISSUE TITLE
Default params

### ISSUE THREAD

**Issue by carsonliu1** [animalStyleFries/FrontEndCapstone-EcommercePage#36]
https://github.com/animalStyleFries/FrontEndCapstone-EcommercePage/blob/2077ba5877110ff56934a42a90464e70d097e7e7/client/src/Main/WidgetMonica/components/MiddleSide/IndividualQuestion.jsx#L17-L18

It is better to have default parameters, (e.g empty objects or arrays as your default) due to errors during the first render of the component.

**Comment by MonicaLiu828** [comment]
Ok, thx for the suggestion, accept and modified~
